### ISSUE TITLE
Error: SyntaxError: Unexpected reserved word when running node offers.js --config=config.json --file=list.txt

### ISSUE THREAD

**Issue by zhoukalex** [automainint/sea-offers-bot-js#1]
Issue:
1. I downloaded the dev main branch through git onto Windows 10
2. Running node v8.11.0
3. I created the config.json & list.txt files, placed those into the /sea-offers-bot-js folder 
4. Navigated to the sea-offers-bot-js folder in command prompt
5. Ran npm install 
6. Tried running node offers.js --config=config.json --file=list.txt, but I get the syntax error below for unexpected reserved word on line 472. Any idea whats going on? 

C:\Users\alex\Documents\GitHub\sea-offers-bot-js\offers.js:472
            for await (const _0x3f238c of _0x1bcece) {
                ^^^^^

SyntaxError: Unexpected reserved word

----------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------
config.json
{
  "network":        "rinkeby",
  "infura_key":     "<removed>",
  "mnemonic":       "<removed>",
  "wallet_address": "<removed>", 
  "price_auto":     false,
  "price_floor":    0.002,
  "price_roof":     100,
  "price_epsilon":  0.001,
  "delay":          500,
  "expiration":     4
}
----------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------
list.txt
https://testnets.opensea.io/assets/0x59f06c3da7dda8720fee43e94ec20f6d20f79048/8 0.01
----------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------
C:\Users\alex\Documents\GitHub\sea-offers-bot-js>npm install

> sea-offers-bot-js@0.2.6 postinstall C:\Users\alex\Documents\GitHub\sea-offers-bot-js
> node hotfix.js

Run hotfix...
* Fix safe-event-emitter error handling.
* Disable opensea-js wETH approval.
Hotfix done.

npm WARN @babel/helper-compilation-targets@7.15.4 requires a peer of @babel/core@^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/helper-define-polyfill-provider@0.2.3 requires a peer of @babel/core@^7.4.0-0 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-transform-runtime@7.15.8 requires a peer of @babel/core@^7.0.0-0 but none is installed. You must install peer dependencies yourself.
npm WARN babel-plugin-polyfill-corejs2@0.2.2 requires a peer of @babel/core@^7.0.0-0 but none is installed. You must install peer dependencies yourself.
npm WARN babel-plugin-polyfill-corejs3@0.2.5 requires a peer of @babel/core@^7.0.0-0 but none is installed. You must install peer dependencies yourself.
npm WARN babel-plugin-polyfill-regenerator@0.2.2 requires a peer of @babel/core@^7.0.0-0 but none is installed. You must install peer dependencies yourself.
npm WARN sea-offers-bot-js@0.2.6 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\watchpack-chokidar2\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

up to date in 7.882s

C:\Users\alex\Documents\GitHub\sea-offers-bot-js>node offers.js --config=config.json --file=list.txt
C:\Users\alex\Documents\GitHub\sea-offers-bot-js\offers.js:472
            for await (const _0x3f238c of _0x1bcece) {
                ^^^^^

SyntaxError: Unexpected reserved word
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

**Comment by automainint** [comment]
Hi! Try update Node.js to last version. I use v14.18.1.

**Comment by automainint** [comment]
Possible fix for this:
https://github.com/automainint/sea-offers-bot-js#troubleshooting

**Comment by automainint** [comment]
Fixed in v0.2.10
