### ISSUE TITLE
Price auto issue

### ISSUE THREAD

**Issue by paulevolve** [automainint/sea-offers-bot-js#10]
Hey, I've been experiencing this problem, don't really know why it happens
I have this asset https://opensea.io/assets/0x3bf2922f4520a8ba0c2efc3d2a1539678dad5e9d/7757 that I tried to bid on
Currently it has a 0.311 weth active offer. 
Price auto is enabled with price floor 0.3 and price roof 0.33. The bot still skips the offer for some reason.
Do you have any idea why?

Here's the config file
`{
  "network": "mainnet",
  "alchemy_key": "",
  "mnemonic": "",
  "wallet_address": "",
  "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.87 Safari/537.36",
  "opensea_key": "",
  "skip_if_order_created": "true",
  "price_auto": "true",
  "price_floor": 0.3,
  "price_roof": 0.33,
  "price_epsilon": 0.001,
  "cookie": "",
  "log_fetch": "true",
  "expiration": "1",
  "delay": "0",
  "discard_threshold": "2",
  "process_timeout": "7000",
  "fetch_timeout": "7000",
  "cache_timeout": "7000",
  "clear_cache_threshold": "2",
  "log_full": "true"
}`

Here's the log

Starting...
Auto price enabled.
Delay per line: 0 ms.

   1 Acquiring asset...
     Address: 0x3bf2922f4520a8ba0c2efc3d2a1539678dad5e9d
     Id:      7757

   Fetching
   https://api.opensea.io/api/v1/asset/0x3bf2922f4520a8ba0c2efc3d2a1539678dad5e9d/7757/?

 * 1 Offer skipped. Price too high.

Done.

Thank you!

**Comment by automainint** [comment]
Bid price will be +10% minimum by default. So, bid price is actually higher than your `roof`.

You can change `price_increment_factor` (value `0.1` means +10%). I don't know current OpenSea limits for price increment, it was +10% minimum some time ago.

**Comment by paulevolve** [comment]
I've set price_increment_factor to 0 and it works perfectly now.
Thank you!
