### ISSUE TITLE
Request was blocked by Cloudflare.

### ISSUE THREAD

**Issue by paulevolve** [automainint/sea-offers-bot-js#4]
I have backconnect rotating proxies +useragent and still get blocked by cloudflare. 
Any idea?

**Comment by automainint** [comment]
Do you have an OpenSea API key?

**Comment by automainint** [comment]
I have some fixes for proxies in new commit.

**Comment by paulevolve** [comment]
Thanks. I'm going to try it

**Comment by paulevolve** [comment]
Does it work without an API?

**Comment by automainint** [comment]
I think, API key is very necessary to do lots of requests. Without an API key your requests will be throttled.
