### ISSUE TITLE
Need to upgrade to OpenSea 2.0

### ISSUE THREAD

**Issue by automainint** [automainint/sea-offers-bot-js#6]
It seems that OpenSea 1.2.8 doesn't work anymore.
I'll upgrade the bot to OpenSea 2.0 when solution for [this issue](https://github.com/ProjectOpenSea/opensea-js/issues/372) will be found.

**Comment by paulevolve** [comment]
Looks like it is fixed: 
https://github.com/ProjectOpenSea/opensea-js/issues/372#issuecomment-1045997109

**Comment by automainint** [comment]
> Looks like it is fixed: [ProjectOpenSea/opensea-js#372 (comment)](https://github.com/ProjectOpenSea/opensea-js/issues/372#issuecomment-1045997109)

Good, I'll check that

**Comment by automainint** [comment]
Fixed in `v0.2.14`
